version: "3.7"

services:
  sqlserver_2019:
    image: mcr.microsoft.com/mssql/server:latest
    hostname: sqlserver_2019
    ports:
      - 1433:1433
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Password1
    volumes:
      - type: volume
        source: data
        target: /var/opt/mssql
volumes:
  data: